# Основные настройки (необходимо заполнить)
api:
  # Ключ API OpenAI
  openai_api_key: ""
  chat_gpt_model: "gpt-4o-mini" # Модель чата гпт

# Настройки работы бота (опционально, можно изменить для персонализации)
settings:
  prompt_tone: "" # Тон ответа в комментарии (должен быть в ковычках)
  comment_limit: 2 # Лимит комментариев на один аккаунт
  sleep_duration: 30 # Пауза после достижения лимита комментариев (в секундах)
  join_channel_delay: 10-30 # Задержка перед подпиской на канал (в секундах)
  send_message_delay: 15-30 # Диапазон задержки перед отправкой сообщения
  random_prompt: false # Выбор случайного пользовательского промпта (true/false)
  detect_language: true # Определять язык поста (true/false)
  accounts_per_proxy: 5 # Аккаунтов на одни прокси